# 站点信息
site_name: MicroBoot  # 文档站点名称
site_description: A sample documentation site  # 文档站点描述
site_author: kk  # 文档作者

# 导航栏
nav:
  - 简介: index.md
  - 快速移植:
      - 基于 CMSIS-PACK 移植 : quick-start/cmsis-pack.md
      - 基于 RT-Thread 软件包移植 : quick-start/RT-Thread.md
      - 基于源码移植: quick-start/quick-start.md
      - 移植常见问题: quick-start/troubleshooting.md
  - 使用指南:
      - 配置: usage-guide/config.md
  - 必备知识: 
      - 变参函数和可变参数宏: utilities/ParameterMacro.md
      - Flash下载算法制作: utilities/FLM.md
  - 组件介绍:
      - queue:  components/queue/queue.md
      - 信号槽: components/signals_slots/signals_slots.md
      - 发布订阅: components/subscribe_publish/subscribe_publish.md
      - 消息地图: components/msg_map/msg_map.md
      - shell: components/shell/shell.md
      - ymodem: components/ymodem/ymodem.md
      - BootLoader: components/bootloader/bootloader.md
      - FlashBlob:  components/flash_blob/flash_blob.md
  - 第三方库:
      - Arm-2D: 3rd-party/Arm-2D/arm_2d.md
      - PLOOC: 3rd-party/plooc/plooc.md
      - FSM: 3rd-party/fsm/fsm.md
  - 开发神器:
      - 简介: tools/microlink/microlink.md
      - RTT: tools/microlink/RTT_printf.md
      - SystemView: tools/microlink/SystemView.md      
      - 脱机下载: tools/microlink/offline_download.md
      - Python API: tools/microlink/python_api.md
  - 参与项目:
      - 如何贡献代码: contribute/code.md
      - 如何贡献文档: contribute/document.md
  - 私人订制:
      - BootLoader: bootloader/BootLoader.md
  - About:
      - Overview: about/about.md
      - Team: about/team.md

# 主题配置
theme:
  name: material  # 使用 Material 主题
  features:
    - navigation.tabs  # 启用选项卡导航
    - navigation.indexes  # 启用索引导航
  palette:
    scheme: default
    primary: indigo
    accent: indigo
 
extra_css:
  - css/custom.css

extra_javascript:
  - https://fonts.googleapis.com/css?family=Fira+Code&display=swap
  
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
      
# GitHub 仓库配置
repo_name: Aladdin-Wang/MicroBoot  # GitHub 用户名和仓库名称
repo_url: https://github.com/Aladdin-Wang/MicroBoot  # GitHub 仓库的 URL
edit_uri: ""  # 如果您的文档在仓库的根目录，可以留空


