name: Build documentation and pack

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  pack:
    name: Generate Pack
    runs-on: ubuntu-latest  # 升级到最新的 Ubuntu 版本
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 使用最新的 v4 版本
        with:
          fetch-depth: 0

      - name: Fetch tags (only for release)
        if: github.event_name == 'release'
        run: git fetch --tags --force

      - name: Setup Node.js
        uses: actions/setup-node@v4  # 使用最新的 v4 版本
        with:
          node-version: '20'

      - name: Make gen_pack.sh executable
        run: chmod +x ./gen_pack.sh

      - name: Generate Pack
        uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.2
          packchk-version: 1.3.96
          gen-pack-script: ./gen_pack.sh
          gen-pack-output: ./output
