jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch --tags --force

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'   

      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-9 libclang-common-9-dev

      - name: Fix missing libclang-cpp.so.9
        run: |
          sudo ln -s /usr/lib/llvm-9/lib/libclang-cpp.so.9 /usr/lib/libclang-cpp.so.9

      - name: Set LD_LIBRARY_PATH
        run: echo "LD_LIBRARY_PATH=/usr/lib/llvm-9/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Make gen_pack.sh executable
        run: chmod +x ./gen_pack.sh

      - name: Generate Pack
        uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.2
          packchk-version: 1.3.96
          gen-pack-script: ./gen_pack.sh
          gen-pack-output: ./output
