name: Build documentation and pack

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch --tags --force
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'   

      - name: Install dependencies for doxygen
        run: |
          sudo apt update
          sudo apt install -y libclang-9-dev doxygen

      - name: Remove existing doxygen symlink if it exists
        run: |
          if [ -L /usr/local/bin/doxygen ]; then
            sudo rm -f /usr/local/bin/doxygen
          elif [ -f /usr/local/bin/doxygen ]; then
            sudo rm -f /usr/local/bin/doxygen
          fi

      - name: Check if doxygen symlink is removed
        run: |
          if [ -L /usr/local/bin/doxygen ]; then
            echo "Symlink still exists, failed to remove"
            exit 1
          fi

      - name: Setup Doxygen symlink
        run: |
          sudo ln -s /opt/doxygen-1.9.2/bin/doxygen /usr/local/bin/doxygen

      - name: Verify doxygen installation
        run: |
          which doxygen
          doxygen --version

      - name: Make gen_pack.sh executable
        run: chmod +x ./gen_pack.sh

      - name: Generate Pack
        uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.2
          packchk-version: 1.3.96
          gen-pack-script: ./gen_pack.sh
          gen-pack-output: ./output
